fix: handle 404 on fip datasource and fix example test.
The `oxide_floating_ip` datasource currently causes a provider error on read
when the ip doesn't exist, e.g.:

```
Error: Provider produced null object

Provider "provider[\"registry.terraform.io/hashicorp/oxide\"]" produced a
null value for
data.oxide_floating_ip.acc-datasource-floating-ip-not-found-627b323c-487b-49ba-a5ec-f60fac65b0d7.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

This happens because the datasource attempts to call
`resp.State.RemoveResource(ctx)` on 404. This is the correct behavior for a
resource, but not for a datasource, and is probably a copy and paste error from
porting the floating ip resource to a datasource. To fix, we drop the state
removal.

We also fix the example test for the floating ip datasource, which had been
skipped due to this error, and due to references to example uuids (also fixed
here).